#version: '3.8'

services:
  db:
    image: postgres:18.3
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    container_name: anylistDB
    volumes:
      - ./pgdata:/var/lib/postgresql

